### ISSUE TITLE
Error: list index out of range

### ISSUE THREAD

**Issue by satishdotpatel** [stackhpc/os-capacity#4]
I have 500 vms running on openstack and have 20 flavors around, when i run your scripts i got following error, i believe its bug not handle to render long list, do you know what is the fix here?

```
[root@ostack-osa os-capacity(keystone_admin)]# os-capacity resources group
Skipping over invalid version data. No stability status in version.
list index out of range
```

**Comment by JohnGarbutt** [comment]
Sorry for confusion, this bit of the code has now been removed, so going to mark this as closed.
